import type { AuthRule } from "@/types/auth-rule.types";

/**
 * Mock auth rules sourced from backend team static JSON.
 *
 * TODO: Replace with live API call when the public endpoint is available:
 *   GET /api/v1/auth-rules?per_page=1000
 *
 * Migration: swap `MOCK_AUTH_RULES` for the `data.data` array from that
 * response and delete this file.
 */
export const MOCK_AUTH_RULES: AuthRule[] = [
  {
    id: 8,
    service: "Data",
    method: "GET",
    pathDsl: "/export/*",
    path_dsl: "/export/*",
    pathRegex: "#^/export/[^/]+$#",
    path_regex: "#^/export/[^/]+$#",
    routeName: null,
    route_name: null,
    rolesAny: null,
    roles_any: null,
    permissionsAny: ["export data"],
    permissions_any: ["export data"],
    permissionsAll: null,
    permissions_all: null,
    store_scope_mode: "none",
    storeScopeMode: "none",
    store_id_sources: null,
    store_match_policy: "all",
    store_allows_empty: false,
    store_all_access_roles_any: null,
    store_all_access_permissions_any: null,
    isActive: true,
    is_active: true,
    priority: 1,
    createdAt: "2026-02-26T15:45:12.000000Z",
    created_at: "2026-02-26T15:45:12.000000Z",
    updatedAt: "2026-02-26T15:45:12.000000Z",
    updated_at: "2026-02-26T15:45:12.000000Z",
  },
  {
    id: 9,
    service: "Data",
    method: "GET",
    pathDsl: "/reports/dspr/**",
    path_dsl: "/reports/dspr/**",
    pathRegex: "#^/reports/dspr/.*$#",
    path_regex: "#^/reports/dspr/.*$#",
    routeName: null,
    route_name: null,
    rolesAny: null,
    roles_any: null,
    permissionsAny: ["reports view"],
    permissions_any: ["reports view"],
    permissionsAll: null,
    permissions_all: null,
    store_scope_mode: "none",
    storeScopeMode: "none",
    store_id_sources: null,
    store_match_policy: "all",
    store_allows_empty: false,
    store_all_access_roles_any: null,
    store_all_access_permissions_any: null,
    isActive: true,
    is_active: true,
    priority: 1,
    createdAt: "2026-02-26T15:51:59.000000Z",
    created_at: "2026-02-26T15:51:59.000000Z",
    updatedAt: "2026-02-26T15:51:59.000000Z",
    updated_at: "2026-02-26T15:51:59.000000Z",
  },
  {
    id: 10,
    service: "Data",
    method: "GET",
    pathDsl: "/engine/keys",
    path_dsl: "/engine/keys",
    pathRegex: "#^/engine/keys$#",
    path_regex: "#^/engine/keys$#",
    routeName: null,
    route_name: null,
    rolesAny: null,
    roles_any: null,
    permissionsAny: ["keys handling"],
    permissions_any: ["keys handling"],
    permissionsAll: null,
    permissions_all: null,
    store_scope_mode: "scoped",
    storeScopeMode: "scoped",
    store_id_sources: null,
    store_match_policy: "all",
    store_allows_empty: false,
    store_all_access_roles_any: null,
    store_all_access_permissions_any: null,
    isActive: true,
    is_active: true,
    priority: 1,
    createdAt: "2026-02-26T15:53:33.000000Z",
    created_at: "2026-02-26T15:53:33.000000Z",
    updatedAt: "2026-02-26T15:53:33.000000Z",
    updated_at: "2026-02-26T15:53:33.000000Z",
  },
  {
    id: 11,
    service: "Data",
    method: "GET",
    pathDsl: "/engine/keys/**",
    path_dsl: "/engine/keys/**",
    pathRegex: "#^/engine/keys/.*$#",
    path_regex: "#^/engine/keys/.*$#",
    routeName: null,
    route_name: null,
    rolesAny: null,
    roles_any: null,
    permissionsAny: ["keys handling"],
    permissions_any: ["keys handling"],
    permissionsAll: null,
    permissions_all: null,
    store_scope_mode: "scoped",
    storeScopeMode: "scoped",
    store_id_sources: null,
    store_match_policy: "all",
    store_allows_empty: false,
    store_all_access_roles_any: null,
    store_all_access_permissions_any: null,
    isActive: true,
    is_active: true,
    priority: 1,
    createdAt: "2026-02-26T15:53:53.000000Z",
    created_at: "2026-02-26T15:53:53.000000Z",
    updatedAt: "2026-02-26T15:53:53.000000Z",
    updated_at: "2026-02-26T15:53:53.000000Z",
  },
  {
    id: 12,
    service: "Data",
    method: "POST",
    pathDsl: "/engine/keys",
    path_dsl: "/engine/keys",
    pathRegex: "#^/engine/keys$#",
    path_regex: "#^/engine/keys$#",
    routeName: null,
    route_name: null,
    rolesAny: null,
    roles_any: null,
    permissionsAny: ["keys handling"],
    permissions_any: ["keys handling"],
    permissionsAll: null,
    permissions_all: null,
    store_scope_mode: "none",
    storeScopeMode: "none",
    store_id_sources: null,
    store_match_policy: "all",
    store_allows_empty: false,
    store_all_access_roles_any: null,
    store_all_access_permissions_any: null,
    isActive: true,
    is_active: true,
    priority: 1,
    createdAt: "2026-02-26T15:54:15.000000Z",
    created_at: "2026-02-26T15:54:15.000000Z",
    updatedAt: "2026-02-26T15:54:15.000000Z",
    updated_at: "2026-02-26T15:54:15.000000Z",
  },
  {
    id: 13,
    service: "Data",
    method: "PUT",
    pathDsl: "/engine/keys/**",
    path_dsl: "/engine/keys/**",
    pathRegex: "#^/engine/keys/.*$#",
    path_regex: "#^/engine/keys/.*$#",
    routeName: null,
    route_name: null,
    rolesAny: null,
    roles_any: null,
    permissionsAny: ["keys handling"],
    permissions_any: ["keys handling"],
    permissionsAll: null,
    permissions_all: null,
    store_scope_mode: "none",
    storeScopeMode: "none",
    store_id_sources: null,
    store_match_policy: "all",
    store_allows_empty: false,
    store_all_access_roles_any: null,
    store_all_access_permissions_any: null,
    isActive: true,
    is_active: true,
    priority: 1,
    createdAt: "2026-02-26T15:55:17.000000Z",
    created_at: "2026-02-26T15:55:17.000000Z",
    updatedAt: "2026-02-26T15:55:17.000000Z",
    updated_at: "2026-02-26T15:55:17.000000Z",
  },
  {
    id: 14,
    service: "Data",
    method: "PATCH",
    pathDsl: "/engine/keys/*",
    path_dsl: "/engine/keys/*",
    pathRegex: "#^/engine/keys/[^/]+$#",
    path_regex: "#^/engine/keys/[^/]+$#",
    routeName: null,
    route_name: null,
    rolesAny: null,
    roles_any: null,
    permissionsAny: ["keys handling"],
    permissions_any: ["keys handling"],
    permissionsAll: null,
    permissions_all: null,
    store_scope_mode: "none",
    storeScopeMode: "none",
    store_id_sources: null,
    store_match_policy: "all",
    store_allows_empty: false,
    store_all_access_roles_any: null,
    store_all_access_permissions_any: null,
    isActive: true,
    is_active: true,
    priority: 1,
    createdAt: "2026-02-26T15:55:52.000000Z",
    created_at: "2026-02-26T15:55:52.000000Z",
    updatedAt: "2026-02-26T15:55:52.000000Z",
    updated_at: "2026-02-26T15:55:52.000000Z",
  },
  {
    id: 15,
    service: "Data",
    method: "DELETE",
    pathDsl: "/engine/keys/*",
    path_dsl: "/engine/keys/*",
    pathRegex: "#^/engine/keys/[^/]+$#",
    path_regex: "#^/engine/keys/[^/]+$#",
    routeName: null,
    route_name: null,
    rolesAny: null,
    roles_any: null,
    permissionsAny: ["keys handling"],
    permissions_any: ["keys handling"],
    permissionsAll: null,
    permissions_all: null,
    store_scope_mode: "none",
    storeScopeMode: "none",
    store_id_sources: null,
    store_match_policy: "all",
    store_allows_empty: false,
    store_all_access_roles_any: null,
    store_all_access_permissions_any: null,
    isActive: true,
    is_active: true,
    priority: 1,
    createdAt: "2026-02-26T15:56:09.000000Z",
    created_at: "2026-02-26T15:56:09.000000Z",
    updatedAt: "2026-02-26T15:56:09.000000Z",
    updated_at: "2026-02-26T15:56:09.000000Z",
  },
  {
    id: 16,
    service: "Data",
    method: "GET",
    pathDsl: "/engine/stores/**",
    path_dsl: "/engine/stores/**",
    pathRegex: "#^/engine/stores/.*$#",
    path_regex: "#^/engine/stores/.*$#",
    routeName: null,
    route_name: null,
    rolesAny: null,
    roles_any: null,
    permissionsAny: ["data entry"],
    permissions_any: ["data entry"],
    permissionsAll: null,
    permissions_all: null,
    store_scope_mode: "none",
    storeScopeMode: "none",
    store_id_sources: null,
    store_match_policy: "all",
    store_allows_empty: false,
    store_all_access_roles_any: null,
    store_all_access_permissions_any: null,
    isActive: true,
    is_active: true,
    priority: 1,
    createdAt: "2026-02-26T15:58:33.000000Z",
    created_at: "2026-02-26T15:58:33.000000Z",
    updatedAt: "2026-02-26T15:58:33.000000Z",
    updated_at: "2026-02-26T15:58:33.000000Z",
  },
  {
    id: 17,
    service: "Data",
    method: "POST",
    pathDsl: "/engine/stores/**",
    path_dsl: "/engine/stores/**",
    pathRegex: "#^/engine/stores/.*$#",
    path_regex: "#^/engine/stores/.*$#",
    routeName: null,
    route_name: null,
    rolesAny: null,
    roles_any: null,
    permissionsAny: ["data entry"],
    permissions_any: ["data entry"],
    permissionsAll: null,
    permissions_all: null,
    store_scope_mode: "none",
    storeScopeMode: "none",
    store_id_sources: null,
    store_match_policy: "all",
    store_allows_empty: false,
    store_all_access_roles_any: null,
    store_all_access_permissions_any: null,
    isActive: true,
    is_active: true,
    priority: 1,
    createdAt: "2026-02-26T15:59:37.000000Z",
    created_at: "2026-02-26T15:59:37.000000Z",
    updatedAt: "2026-02-26T15:59:37.000000Z",
    updated_at: "2026-02-26T15:59:37.000000Z",
  },
  {
    id: 18,
    service: "Data",
    method: "GET",
    pathDsl: "/manual-import",
    path_dsl: "/manual-import",
    pathRegex: "#^/manual\\-import$#",
    path_regex: "#^/manual\\-import$#",
    routeName: null,
    route_name: null,
    rolesAny: null,
    roles_any: null,
    permissionsAny: ["import data"],
    permissions_any: ["import data"],
    permissionsAll: null,
    permissions_all: null,
    store_scope_mode: "none",
    storeScopeMode: "none",
    store_id_sources: null,
    store_match_policy: "all",
    store_allows_empty: false,
    store_all_access_roles_any: null,
    store_all_access_permissions_any: null,
    isActive: true,
    is_active: true,
    priority: 1,
    createdAt: "2026-02-26T16:00:45.000000Z",
    created_at: "2026-02-26T16:00:45.000000Z",
    updatedAt: "2026-02-26T16:00:45.000000Z",
    updated_at: "2026-02-26T16:00:45.000000Z",
  },
  {
    id: 19,
    service: "Data",
    method: "GET",
    pathDsl: "/manual-import/**",
    path_dsl: "/manual-import/**",
    pathRegex: "#^/manual\\-import/.*$#",
    path_regex: "#^/manual\\-import/.*$#",
    routeName: null,
    route_name: null,
    rolesAny: null,
    roles_any: null,
    permissionsAny: ["import data"],
    permissions_any: ["import data"],
    permissionsAll: null,
    permissions_all: null,
    store_scope_mode: "none",
    storeScopeMode: "none",
    store_id_sources: null,
    store_match_policy: "all",
    store_allows_empty: false,
    store_all_access_roles_any: null,
    store_all_access_permissions_any: null,
    isActive: true,
    is_active: true,
    priority: 1,
    createdAt: "2026-02-26T16:00:56.000000Z",
    created_at: "2026-02-26T16:00:56.000000Z",
    updatedAt: "2026-02-26T16:00:56.000000Z",
    updated_at: "2026-02-26T16:00:56.000000Z",
  },
  {
    id: 20,
    service: "Data",
    method: "POST",
    pathDsl: "/manual-import/*",
    path_dsl: "/manual-import/*",
    pathRegex: "#^/manual\\-import/[^/]+$#",
    path_regex: "#^/manual\\-import/[^/]+$#",
    routeName: null,
    route_name: null,
    rolesAny: null,
    roles_any: null,
    permissionsAny: ["import data"],
    permissions_any: ["import data"],
    permissionsAll: null,
    permissions_all: null,
    store_scope_mode: "none",
    storeScopeMode: "none",
    store_id_sources: null,
    store_match_policy: "all",
    store_allows_empty: false,
    store_all_access_roles_any: null,
    store_all_access_permissions_any: null,
    isActive: true,
    is_active: true,
    priority: 1,
    createdAt: "2026-02-26T16:01:31.000000Z",
    created_at: "2026-02-26T16:01:31.000000Z",
    updatedAt: "2026-02-26T16:01:31.000000Z",
    updated_at: "2026-02-26T16:01:31.000000Z",
  },
  {
    id: 38,
    service: "QA",
    method: "GET",
    pathDsl: "/audits/ratings-summary/**",
    path_dsl: "/audits/ratings-summary/**",
    pathRegex: "#^/audits/ratings-summary/.*$#",
    path_regex: "#^/audits/ratings-summary/.*$#",
    routeName: null,
    route_name: null,
    rolesAny: [],
    roles_any: [],
    permissionsAny: ["reports view"],
    permissions_any: ["reports view"],
    permissionsAll: [],
    permissions_all: [],
    store_scope_mode: "scoped",
    storeScopeMode: "scoped",
    store_id_sources: null,
    store_match_policy: "all",
    store_allows_empty: false,
    store_all_access_roles_any: [],
    store_all_access_permissions_any: [],
    isActive: true,
    is_active: true,
    priority: 10,
    createdAt: "2026-02-26T16:10:33.000000Z",
    created_at: "2026-02-26T16:10:33.000000Z",
    updatedAt: "2026-02-26T16:10:33.000000Z",
    updated_at: "2026-02-26T16:10:33.000000Z",
  },
  {
    id: 39,
    service: "QA",
    method: "POST",
    pathDsl: "/camera-forms",
    path_dsl: "/camera-forms",
    pathRegex: "#^/camera-forms$#",
    path_regex: "#^/camera-forms$#",
    routeName: null,
    route_name: null,
    rolesAny: [],
    roles_any: [],
    permissionsAny: ["qa audit"],
    permissions_any: ["qa audit"],
    permissionsAll: [],
    permissions_all: [],
    store_scope_mode: "none",
    storeScopeMode: "none",
    store_id_sources: null,
    store_match_policy: "all",
    store_allows_empty: false,
    store_all_access_roles_any: [],
    store_all_access_permissions_any: [],
    isActive: true,
    is_active: true,
    priority: 20,
    createdAt: "2026-02-26T16:10:33.000000Z",
    created_at: "2026-02-26T16:10:33.000000Z",
    updatedAt: "2026-02-26T16:10:33.000000Z",
    updated_at: "2026-02-26T16:10:33.000000Z",
  },
  {
    id: 40,
    service: "QA",
    method: "PUT",
    pathDsl: "/camera-forms/*",
    path_dsl: "/camera-forms/*",
    pathRegex: "#^/camera-forms/[^/]+$#",
    path_regex: "#^/camera-forms/[^/]+$#",
    routeName: null,
    route_name: null,
    rolesAny: [],
    roles_any: [],
    permissionsAny: ["qa audit"],
    permissions_any: ["qa audit"],
    permissionsAll: [],
    permissions_all: [],
    store_scope_mode: "none",
    storeScopeMode: "none",
    store_id_sources: null,
    store_match_policy: "all",
    store_allows_empty: false,
    store_all_access_roles_any: [],
    store_all_access_permissions_any: [],
    isActive: true,
    is_active: true,
    priority: 21,
    createdAt: "2026-02-26T16:10:33.000000Z",
    created_at: "2026-02-26T16:10:33.000000Z",
    updatedAt: "2026-02-26T16:10:33.000000Z",
    updated_at: "2026-02-26T16:10:33.000000Z",
  },
  {
    id: 41,
    service: "QA",
    method: "PATCH",
    pathDsl: "/camera-forms/*",
    path_dsl: "/camera-forms/*",
    pathRegex: "#^/camera-forms/[^/]+$#",
    path_regex: "#^/camera-forms/[^/]+$#",
    routeName: null,
    route_name: null,
    rolesAny: [],
    roles_any: [],
    permissionsAny: ["qa audit"],
    permissions_any: ["qa audit"],
    permissionsAll: [],
    permissions_all: [],
    store_scope_mode: "none",
    storeScopeMode: "none",
    store_id_sources: null,
    store_match_policy: "all",
    store_allows_empty: false,
    store_all_access_roles_any: [],
    store_all_access_permissions_any: [],
    isActive: true,
    is_active: true,
    priority: 22,
    createdAt: "2026-02-26T16:10:33.000000Z",
    created_at: "2026-02-26T16:10:33.000000Z",
    updatedAt: "2026-02-26T16:10:33.000000Z",
    updated_at: "2026-02-26T16:10:33.000000Z",
  },
  {
    id: 42,
    service: "QA",
    method: "DELETE",
    pathDsl: "/camera-forms/*",
    path_dsl: "/camera-forms/*",
    pathRegex: "#^/camera-forms/[^/]+$#",
    path_regex: "#^/camera-forms/[^/]+$#",
    routeName: null,
    route_name: null,
    rolesAny: [],
    roles_any: [],
    permissionsAny: ["qa audit"],
    permissions_any: ["qa audit"],
    permissionsAll: [],
    permissions_all: [],
    store_scope_mode: "none",
    storeScopeMode: "none",
    store_id_sources: null,
    store_match_policy: "all",
    store_allows_empty: false,
    store_all_access_roles_any: [],
    store_all_access_permissions_any: [],
    isActive: true,
    is_active: true,
    priority: 23,
    createdAt: "2026-02-26T16:10:33.000000Z",
    created_at: "2026-02-26T16:10:33.000000Z",
    updatedAt: "2026-02-26T16:10:33.000000Z",
    updated_at: "2026-02-26T16:10:33.000000Z",
  },
  {
    id: 43,
    service: "QA",
    method: "POST",
    pathDsl: "/custom-reports",
    path_dsl: "/custom-reports",
    pathRegex: "#^/custom-reports$#",
    path_regex: "#^/custom-reports$#",
    routeName: null,
    route_name: null,
    rolesAny: [],
    roles_any: [],
    permissionsAny: ["qa audit"],
    permissions_any: ["qa audit"],
    permissionsAll: [],
    permissions_all: [],
    store_scope_mode: "none",
    storeScopeMode: "none",
    store_id_sources: null,
    store_match_policy: "all",
    store_allows_empty: false,
    store_all_access_roles_any: [],
    store_all_access_permissions_any: [],
    isActive: true,
    is_active: true,
    priority: 30,
    createdAt: "2026-02-26T16:10:33.000000Z",
    created_at: "2026-02-26T16:10:33.000000Z",
    updatedAt: "2026-02-26T16:10:33.000000Z",
    updated_at: "2026-02-26T16:10:33.000000Z",
  },
  {
    id: 44,
    service: "QA",
    method: "PUT",
    pathDsl: "/custom-reports/*",
    path_dsl: "/custom-reports/*",
    pathRegex: "#^/custom-reports/[^/]+$#",
    path_regex: "#^/custom-reports/[^/]+$#",
    routeName: null,
    route_name: null,
    rolesAny: [],
    roles_any: [],
    permissionsAny: ["qa audit"],
    permissions_any: ["qa audit"],
    permissionsAll: [],
    permissions_all: [],
    store_scope_mode: "none",
    storeScopeMode: "none",
    store_id_sources: null,
    store_match_policy: "all",
    store_allows_empty: false,
    store_all_access_roles_any: [],
    store_all_access_permissions_any: [],
    isActive: true,
    is_active: true,
    priority: 31,
    createdAt: "2026-02-26T16:10:33.000000Z",
    created_at: "2026-02-26T16:10:33.000000Z",
    updatedAt: "2026-02-26T16:10:33.000000Z",
    updated_at: "2026-02-26T16:10:33.000000Z",
  },
  {
    id: 45,
    service: "QA",
    method: "PATCH",
    pathDsl: "/custom-reports/*",
    path_dsl: "/custom-reports/*",
    pathRegex: "#^/custom-reports/[^/]+$#",
    path_regex: "#^/custom-reports/[^/]+$#",
    routeName: null,
    route_name: null,
    rolesAny: [],
    roles_any: [],
    permissionsAny: ["qa audit"],
    permissions_any: ["qa audit"],
    permissionsAll: [],
    permissions_all: [],
    store_scope_mode: "none",
    storeScopeMode: "none",
    store_id_sources: null,
    store_match_policy: "all",
    store_allows_empty: false,
    store_all_access_roles_any: [],
    store_all_access_permissions_any: [],
    isActive: true,
    is_active: true,
    priority: 32,
    createdAt: "2026-02-26T16:10:33.000000Z",
    created_at: "2026-02-26T16:10:33.000000Z",
    updatedAt: "2026-02-26T16:10:33.000000Z",
    updated_at: "2026-02-26T16:10:33.000000Z",
  },
  {
    id: 46,
    service: "QA",
    method: "DELETE",
    pathDsl: "/custom-reports/*",
    path_dsl: "/custom-reports/*",
    pathRegex: "#^/custom-reports/[^/]+$#",
    path_regex: "#^/custom-reports/[^/]+$#",
    routeName: null,
    route_name: null,
    rolesAny: [],
    roles_any: [],
    permissionsAny: ["qa audit"],
    permissions_any: ["qa audit"],
    permissionsAll: [],
    permissions_all: [],
    store_scope_mode: "none",
    storeScopeMode: "none",
    store_id_sources: null,
    store_match_policy: "all",
    store_allows_empty: false,
    store_all_access_roles_any: [],
    store_all_access_permissions_any: [],
    isActive: true,
    is_active: true,
    priority: 33,
    createdAt: "2026-02-26T16:10:33.000000Z",
    created_at: "2026-02-26T16:10:33.000000Z",
    updatedAt: "2026-02-26T16:10:33.000000Z",
    updated_at: "2026-02-26T16:10:33.000000Z",
  },
  {
    id: 47,
    service: "QA",
    method: "POST",
    pathDsl: "/entities",
    path_dsl: "/entities",
    pathRegex: "#^/entities$#",
    path_regex: "#^/entities$#",
    routeName: null,
    route_name: null,
    rolesAny: [],
    roles_any: [],
    permissionsAny: ["qa admin"],
    permissions_any: ["qa admin"],
    permissionsAll: [],
    permissions_all: [],
    store_scope_mode: "none",
    storeScopeMode: "none",
    store_id_sources: null,
    store_match_policy: "all",
    store_allows_empty: false,
    store_all_access_roles_any: [],
    store_all_access_permissions_any: [],
    isActive: true,
    is_active: true,
    priority: 40,
    createdAt: "2026-02-26T16:10:33.000000Z",
    created_at: "2026-02-26T16:10:33.000000Z",
    updatedAt: "2026-02-26T16:10:33.000000Z",
    updated_at: "2026-02-26T16:10:33.000000Z",
  },
  {
    id: 48,
    service: "QA",
    method: "PUT",
    pathDsl: "/entities/*",
    path_dsl: "/entities/*",
    pathRegex: "#^/entities/[^/]+$#",
    path_regex: "#^/entities/[^/]+$#",
    routeName: null,
    route_name: null,
    rolesAny: [],
    roles_any: [],
    permissionsAny: ["qa admin"],
    permissions_any: ["qa admin"],
    permissionsAll: [],
    permissions_all: [],
    store_scope_mode: "none",
    storeScopeMode: "none",
    store_id_sources: null,
    store_match_policy: "all",
    store_allows_empty: false,
    store_all_access_roles_any: [],
    store_all_access_permissions_any: [],
    isActive: true,
    is_active: true,
    priority: 41,
    createdAt: "2026-02-26T16:10:33.000000Z",
    created_at: "2026-02-26T16:10:33.000000Z",
    updatedAt: "2026-02-26T16:10:33.000000Z",
    updated_at: "2026-02-26T16:10:33.000000Z",
  },
  {
    id: 49,
    service: "QA",
    method: "PATCH",
    pathDsl: "/entities/*",
    path_dsl: "/entities/*",
    pathRegex: "#^/entities/[^/]+$#",
    path_regex: "#^/entities/[^/]+$#",
    routeName: null,
    route_name: null,
    rolesAny: [],
    roles_any: [],
    permissionsAny: ["qa admin"],
    permissions_any: ["qa admin"],
    permissionsAll: [],
    permissions_all: [],
    store_scope_mode: "none",
    storeScopeMode: "none",
    store_id_sources: null,
    store_match_policy: "all",
    store_allows_empty: false,
    store_all_access_roles_any: [],
    store_all_access_permissions_any: [],
    isActive: true,
    is_active: true,
    priority: 42,
    createdAt: "2026-02-26T16:10:33.000000Z",
    created_at: "2026-02-26T16:10:33.000000Z",
    updatedAt: "2026-02-26T16:10:33.000000Z",
    updated_at: "2026-02-26T16:10:33.000000Z",
  },
  {
    id: 50,
    service: "QA",
    method: "DELETE",
    pathDsl: "/entities/*",
    path_dsl: "/entities/*",
    pathRegex: "#^/entities/[^/]+$#",
    path_regex: "#^/entities/[^/]+$#",
    routeName: null,
    route_name: null,
    rolesAny: [],
    roles_any: [],
    permissionsAny: ["qa admin"],
    permissions_any: ["qa admin"],
    permissionsAll: [],
    permissions_all: [],
    store_scope_mode: "none",
    storeScopeMode: "none",
    store_id_sources: null,
    store_match_policy: "all",
    store_allows_empty: false,
    store_all_access_roles_any: [],
    store_all_access_permissions_any: [],
    isActive: true,
    is_active: true,
    priority: 43,
    createdAt: "2026-02-26T16:10:33.000000Z",
    created_at: "2026-02-26T16:10:33.000000Z",
    updatedAt: "2026-02-26T16:10:33.000000Z",
    updated_at: "2026-02-26T16:10:33.000000Z",
  },
  {
    id: 51,
    service: "QA",
    method: "POST",
    pathDsl: "/categories",
    path_dsl: "/categories",
    pathRegex: "#^/categories$#",
    path_regex: "#^/categories$#",
    routeName: null,
    route_name: null,
    rolesAny: [],
    roles_any: [],
    permissionsAny: ["qa admin"],
    permissions_any: ["qa admin"],
    permissionsAll: [],
    permissions_all: [],
    store_scope_mode: "none",
    storeScopeMode: "none",
    store_id_sources: null,
    store_match_policy: "all",
    store_allows_empty: false,
    store_all_access_roles_any: [],
    store_all_access_permissions_any: [],
    isActive: true,
    is_active: true,
    priority: 50,
    createdAt: "2026-02-26T16:10:33.000000Z",
    created_at: "2026-02-26T16:10:33.000000Z",
    updatedAt: "2026-02-26T16:10:33.000000Z",
    updated_at: "2026-02-26T16:10:33.000000Z",
  },
  {
    id: 52,
    service: "QA",
    method: "PUT",
    pathDsl: "/categories/*",
    path_dsl: "/categories/*",
    pathRegex: "#^/categories/[^/]+$#",
    path_regex: "#^/categories/[^/]+$#",
    routeName: null,
    route_name: null,
    rolesAny: [],
    roles_any: [],
    permissionsAny: ["qa admin"],
    permissions_any: ["qa admin"],
    permissionsAll: [],
    permissions_all: [],
    store_scope_mode: "none",
    storeScopeMode: "none",
    store_id_sources: null,
    store_match_policy: "all",
    store_allows_empty: false,
    store_all_access_roles_any: [],
    store_all_access_permissions_any: [],
    isActive: true,
    is_active: true,
    priority: 51,
    createdAt: "2026-02-26T16:10:33.000000Z",
    created_at: "2026-02-26T16:10:33.000000Z",
    updatedAt: "2026-02-26T16:10:33.000000Z",
    updated_at: "2026-02-26T16:10:33.000000Z",
  },
  {
    id: 53,
    service: "QA",
    method: "PATCH",
    pathDsl: "/categories/*",
    path_dsl: "/categories/*",
    pathRegex: "#^/categories/[^/]+$#",
    path_regex: "#^/categories/[^/]+$#",
    routeName: null,
    route_name: null,
    rolesAny: [],
    roles_any: [],
    permissionsAny: ["qa admin"],
    permissions_any: ["qa admin"],
    permissionsAll: [],
    permissions_all: [],
    store_scope_mode: "none",
    storeScopeMode: "none",
    store_id_sources: null,
    store_match_policy: "all",
    store_allows_empty: false,
    store_all_access_roles_any: [],
    store_all_access_permissions_any: [],
    isActive: true,
    is_active: true,
    priority: 52,
    createdAt: "2026-02-26T16:10:33.000000Z",
    created_at: "2026-02-26T16:10:33.000000Z",
    updatedAt: "2026-02-26T16:10:33.000000Z",
    updated_at: "2026-02-26T16:10:33.000000Z",
  },
  {
    id: 54,
    service: "QA",
    method: "DELETE",
    pathDsl: "/categories/*",
    path_dsl: "/categories/*",
    pathRegex: "#^/categories/[^/]+$#",
    path_regex: "#^/categories/[^/]+$#",
    routeName: null,
    route_name: null,
    rolesAny: [],
    roles_any: [],
    permissionsAny: ["qa admin"],
    permissions_any: ["qa admin"],
    permissionsAll: [],
    permissions_all: [],
    store_scope_mode: "none",
    storeScopeMode: "none",
    store_id_sources: null,
    store_match_policy: "all",
    store_allows_empty: false,
    store_all_access_roles_any: [],
    store_all_access_permissions_any: [],
    isActive: true,
    is_active: true,
    priority: 53,
    createdAt: "2026-02-26T16:10:33.000000Z",
    created_at: "2026-02-26T16:10:33.000000Z",
    updatedAt: "2026-02-26T16:10:33.000000Z",
    updated_at: "2026-02-26T16:10:33.000000Z",
  },
];
